import = ["~/.config/alacritty/tokyo-night.toml"]

[font]

size = 14.0

[font.bold]

family = "DankMono Nerd Font"


[font.bold_italic]

family = "DankMono Nerd Font"


[font.italic]

family = "DankMono Nerd Font"


[font.normal]

family = "DankMono Nerd Font"


[window]
opacity = 0.9
